### ISSUE TITLE
Easy way to recover which tips from original tree have been kept, swapped, or dropped

### ISSUE THREAD

**Issue by mwpennell** [richfitz/phyndr#10]
Think this would be useful for people I think, as it is not obvious how to do it given that the taxon labels on the new tree have been replaced.

**Comment by richfitz** [comment]
Sure, we can add some bookkeeping in there as we collapse the groups.

**Comment by mwpennell** [comment]
Have we addressed this? Obviously fairly straightforward to do this posthoc but seems like this might be a useful little utility to have around

```
idx  <- which(new$tip.label %in% old$tip.label) 
same <- new$tip.label[idx]
swap <- new$tip.label[-idx]
```
