### ISSUE TITLE
Traitless phyndr

### ISSUE THREAD

**Issue by mwpennell** [richfitz/phyndr#13]
Tank approached with a use case that I think the phyndr machinery could be used for albeit in a slightly modified form
1. He wants to do diversification analyses using unresolved clades as tips. 
2. To get the unresolved clades, he wants to collapse the tree such that no named groups are paraphyletic
3. Wants a list of all named groups contained in the unresolved clades, such that he can get species richnesses from `TaxonLookup::lookup_table`

This is a combination of the taxonomic and topological versions of phyndr (without trait names). Think that our algorithm could be tweaked to return this without too much trouble and then it might be a common use case.

thoughts?

**Comment by richfitz** [comment]
Hmm, interesting.  Could be done, but let's hold off until we get the paper submitted (unless you want to take a crack at it)

**Comment by mwpennell** [comment]
I think this is outside of the purview of what we want to do and a student in the O'Meara lab appears to have tackled this problem independently https://github.com/oschwery/MonoPhy 

abandon this for now
