### ISSUE TITLE
sample from output

### ISSUE THREAD

**Issue by mwpennell** [richfitz/phyndr#21]
so one of the things we mention in the paper is that one could run analyses across multiple permutations in the data but (unless i am missing something), we didn't write any code to do this. i posted a little code (not tested) https://github.com/richfitz/phyndr/commit/2cc4a8d56c8cf181ec51be880b20b9314c6980d8 only to raise a few problem: how do we return x datasets?
- if the number of permutations is small, we can easily get them all but how do you prevent overflow in calculating the number of permutations
- how do you figure out if a request number x is larger than R can handle. what should the correct behaviour be
- if a user wants 100 datasets, how can return 100 datasets if the possible number of permutations is > 100 and the exact number of permutations if less. and say there are exactly 100 permutations possible, how do we get them all. if we sample randomly, this may take a long time. we could also just do it systematically but this will lead to more changes early on.

i just wanted to put the code out there to get people thinking of this. francois brought this up in his review as well and I think it is worth devoting some consideration to.

**Comment by richfitz** [comment]
Even though you have an answer on twitter, I'd stop well ahead of that number.  The function could take a maxn argument that would be maximum number of trees you're willing to deal with.  I think retuning a generating function (which I thought we'd implemented) is the best bet - it can yield trees infinitely.

**Comment by mwpennell** [comment]
Hmmm...not sure what i was thinking her :/ completely forgot we (you) implemented that sampling function. agree that's a good solution and we should (probably) just stick with that. i guess if someone wants exactly 100 unique permutations of the data and the number of possible permutations is close to 100, they'll have to have the generating function return some number more than that and just pare down to the unique ones.
